spring:
  application:
    name: Shnurok

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: DaiMneSil1
    url: jdbc:mysql://localhost:3305/mydb
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update

jwt:
  secret: secret
  expirationMs: 3600000

server:
  port: 8080
